[build]
  functions = "build" # Build directory for lambda functions
  command = "npm run build"

# Different environments based on context
# On production, devDependencies will not be installed
[build.environment]
  NODE_ENV = "development"
[context.production.environment]
  NODE_ENV = "production"
